server:
  port: 8080

spring:
  application:
    name: demo-application
  datasource:
    url: jdbc:postgresql://172.16.8.135:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: HikariCP
      initialization-fail-timeout: 60000
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true

# Cấu hình JWT
app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration: 86400000
    header: Bearer
    cookie-name: jwt-token

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
    org.springframework.boot.devtools: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springdoc: DEBUG