server:
  port: 8080

spring:
  application:
    name: demo-application
  datasource:
    url: jdbc:postgresql://db:5555/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG